### ISSUE TITLE
Compare with your first paper

### ISSUE THREAD

**Issue by DCNSW** [itailang/SampleNet#12]
Thanks for your great contributions on point cloud downsampling. I'd like to ask some questions if you don't mind.

In this paper, when training the sample net, you use the **R** (sub-point cloud) after [softly projection](https://github.com/itailang/SampleNet/blob/master/classification/train_samplenet.py#L169) as the input of the task network.
However, in your [first paper](https://arxiv.org/abs/1812.01659), you use the [generated point cloud](https://github.com/orendv/learning_to_sample/blob/master/classification/train_SNET.py#L125) but not the "hard projection" point cloud after [nn_matching](https://github.com/orendv/learning_to_sample/blob/master/classification/evaluate_SNET.py#L160) as the input of the task network.
Why not unify the two algorithms?

Thank you for your reply.

**Comment by itailang** [comment]
Dear @DCNSW,

SampleNet (from SampleNet paper) is an extension of S-NET (form Learning to Sample paper). In the second paper, I added a soft projection module before feeding the points to the task network. This module turned the generated point cloud into a softly projected point cloud. It enabled to learn an optimal sampling strategy in a differentiable manner, rather than learning a simplification of the original point cloud. Thus, you can view the second algorithm is an improvement of the first one.

Hope it answers your question. If you have further questions, please share them.

**Comment by DCNSW** [comment]
Thanks for your quick reply very much.

I have understand what you mean, but why didn't you use the point cloud after [nn_matching](https://github.com/orendv/learning_to_sample/blob/master/classification/evaluate_SNET.py#L160) (hard projection) as the input of the task network in your first paper when training the sample network? It can be considered a special case of the "[soft projection](https://github.com/itailang/SampleNet/blob/master/classification/train_samplenet.py#L169)" (in this case, each point is projected onto 1 nearest neighbor).

**Comment by itailang** [comment]
Hard projection is a non-differentiable operation, and thus, cannot be used during training.

Soft projection, on the other hand, is a differentiable operation. It is optimized during training to approximate hard projection, which is done during testing.
